### ISSUE TITLE
Help needed in setting up testing

### ISSUE THREAD

**Issue by Karyum** [FACN1/PAS-MVP#17]
@esraajb  we cant find any good documentation on how to setup testing in our project can you point us to any resources ?

**Comment by jbesraa** [comment]
You can use tape(we have already used it in the course) with [enzyme.](https://github.com/airbnb/enzyme/blob/master/docs/guides/tape-ava.md)

**Comment by jbesraa** [comment]
http://12devsofxmas.co.uk/2015/12/day-2-testing-react-applications/
